default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: loaner_development
  username: loaner_user
  password:

test: &test
  <<: *default
  database: loaner_test
  username: loaner_user
  password:

cucumber:
  <<: *test